### ISSUE TITLE
Composer update

### ISSUE THREAD

**Issue by aureliusm** [Simettric/DoctrineTranslatableFormBundle#1]
Hi,

can you please update composer file to include Symfony 3.1.\* and above.. now there are problems "Your requirements could not be resolved to an installable set of packages.".

Is this plugin actively developed?

Thanks

**Comment by asiermarques** [comment]
Yes, it is.

Thanks for your issue. I´m using this bundle in production with Symfony 3.0.\* projects.

I´ve updated now the Symfony version in the composer file and create a tag with the new version.
