### ISSUE TITLE
DataMapper tries to map SubmitType

### ISSUE THREAD

**Issue by Alumbrados** [Simettric/DoctrineTranslatableFormBundle#4]
When adding a button i get the following exception:

`Neither the property "submit" nor one of the methods "getSubmit()", "submit()", "isSubmit()", "hasSubmit()", "__get()" exist and have public access in class "AppBundle\Entity\Category".`

Looks like it wants to map a value to the SubmitType from the entity. This value obviously don't exist, and since SubmitType doesn't have a mapped => false option, there is currently no way to use buttons.

**Comment by Alumbrados** [comment]
The button turns null instead of false, so this fixes it:

``` php
if (false === $form->getConfig()->getOption("mapped") || null === $form->getConfig()->getOption("mapped")){
    continue;
}
```

**Comment by asiermarques** [comment]
Thanks!, added the fix

**Comment by Alumbrados** [comment]
Its required on both mapDataToForms and mapFormsToData
