### ISSUE TITLE
One tab for each language and all form tranlslated fields

### ISSUE THREAD

**Issue by mkalisz77** [Simettric/DoctrineTranslatableFormBundle#6]
For now each field has own locale tabs

Eg.

en es de
title

en es de
subtitle
...

Is it possible to have one language tab for all fields

en es de
title
subtitle

**Comment by asiermarques** [comment]
At this moment the bundle doesn´t offer a view for achieve that but you can overwrite the template simettric/doctrine-translatable-form-bundle/Resources/views/Form/fields.html.twig in your app directory and then implement your own UI.
