### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by salimmejdoub** [Simettric/DoctrineTranslatableFormBundle#9]
How can i make the locales appear once not for every input

thanks

**Comment by asiermarques** [comment]
The best approach is overwrite the template https://github.com/Simettric/DoctrineTranslatableFormBundle/blob/master/Resources/views/Form/fields.html.twig in your app directory, removing the tabs and with javascript, control what tabpanels need to be shown with a custom menu.

**Comment by salimmejdoub** [comment]
the prob is when i put the for outside the blocks 
i can'T  display the tabs
